### ISSUE TITLE
Inconsistency in description of repo

### ISSUE THREAD

**Issue by ahmed1490** [dmfrancisco/JS.coach#11]
https://js.coach/all/itsa-react-input

on js.coach the description says "textarea element"
on the github page it says.. "input element"

**Comment by dmfrancisco** [comment]
Nice catch! It seems there's a [new version](https://github.com/ItsAsbreuk/itsa-react-input/commit/c580ce6377d7bba30be9c90f7a4fbeec82b32236) with a new description but the scripts haven't updated this package yet, because sometimes it takes a couple hours. I forced the update manually now. Thanks :+1:

**Comment by ahmed1490** [comment]
Wondering if the last commit should be shown for each repo. 
Helps in this case. I simply know the last commit is not updated plus good to see quick view what new went in.

**Comment by dmfrancisco** [comment]
That's interesting :+1: I'll add as a feature request.
