### ISSUE TITLE
Popular Tab Update!

### ISSUE THREAD

**Issue by dcflow** [dmfrancisco/JS.coach#13]
Hi,

If the packages are sorted by popularity the details page shows only the page on which the package
was filed under.

Thank You!

**Comment by dmfrancisco** [comment]
Hi @DHidee66! React, Babel, Webpack and others follow the monorepo approach, in which a single git repository is used for multiple packages. Because both readme and stars come from GitHub, and the React, Babel and Webpack repos are more popular than the community packages, when you sort by popular you get those first. And the readme is always the same. So it's not a bug, but it's definitely not ideal.

**Comment by dmfrancisco** [comment]
Not sure if I explained it well enough 😛 Thank you for taking the time to raise the issue!

**Comment by DHidee66** [comment]
So it's a feature not a bug :) Thank you for you great explanation.

**Comment by dmfrancisco** [comment]
No problem! We currently get the READMEs already rendered via GitHub API. This allows us to support GitHub Task Lists for example, allows to be sure that the README always looks as expected, and also support READMEs that are not written in Markdown. But for these particular cases, where there are several READMEs per repository, it would be preferable to use the README NPM provides.

I'll create a new feature request! Thanks again :+1:
