### ISSUE TITLE
Reconsider UI?

### ISSUE THREAD

**Issue by nickhudkins** [dmfrancisco/JS.coach#148]
Hi. Today I learned that react.parts is being superseded by js.coach and became very sad because while the scope of the project grew to include more than just react (YAY) it became more frustrating to use.
# This is able to be read:

It has:
1. Hierarchy
2. Iconography to help quick consumption of information
3. Contrast.
4. Large enough text that it doesn't hurt your eyes.

![nice](https://s3.amazonaws.com/f.cl.ly/items/1n0w2C2T0j2p2d3R1j1U/Screen%20Shot%202016-07-05%20at%201.58.32%20PM.png?v=3a7b1bba)
# This is more difficult to read:

It has:
1. Odd hierarchy (e.g. the search box is between the menu and logo, and is missed easily)
2. Filters that have no labeling as to what they are (I now realize they are filters)
3. Arbitrarily pinned items?
4. Very low contrast
5. TSS (too small syndrome) everything is so small :(

![difficult](https://s3.amazonaws.com/f.cl.ly/items/0Y3d192T2l2Z0f3q1F3J/Screen%20Shot%202016-07-05%20at%201.59.51%20PM.png?v=1412f358)

I'd be more than willing to offer additional / more specific feedback if it's not just me that's struggling with this.

**Comment by dmfrancisco** [comment]
Hello @nickhudkins, thanks for your feedback! 👍 

Yes, [React.parts](https://react.parts) has not been updated for 5 months now. The top banner was added prior to this so people could move to [JS.coach](https://js.coach) or use one of the alternatives, such as the great [react-components.com](https://react-components.com).

#### Some context

My problems with React.parts were:
- It was time consuming to keep the catalog updated. The new scripts are almost totally automated.
- Showing the README in the main column was not ideal. With Google Analytics I found out that 71% of our users had at least a resolution of 1440x900 so using a two column layout was preferable.
- I wanted to include more categories besides React and the horizontal tabs approach didn't work.

At the time I was also planning to add more features, such as:
- Saving packages (the Pinned section)
- Including a "quality raking" (using stars, the # of dependent packages, [packagequality.com](http://packagequality.com), …)
- Filtering out packages with unmet dependencies by uploading a `package.json` file
- Better search

Unfortunately I ran out of time to work on this and so haven't updated it in a while.

#### Regarding your feedback

1. Yes, totally agree.
2. The only filters without a label are the top ones, which in my opinion are straightforward.
3. If I understand what you mean, you are referring to the "Pinned" section that was not implemented. This was due to lack of free time. I left it there with a subscribe field to see if people were interested in it (so far around 100 people entered their email).
4. In my opinion, the contrast is good, since it's mostly `#000` text over a `#fff` background.
5. For the majority of our users, I think the text is not that small. I guess it is compared to React.parts and some modern websites, but I'm able to read everything well and can see a lot of information without scrolling.

#### What I think needs improving in terms of UI

- The font is very hard to read in Windows
- The font is too small in mobile devices and you can't see the READMEs
- The Ad location is bad
- The Search field and Menu are weird

Thanks again for your feedback 👍  Feel free to submit a PR but, since I don't agree with all your points, I can't guarantee I'll include all your changes 😕  Let me know what you think! I'm happy to point the React.parts domain to another server if you are willing to keep the catalog updated.

**Comment by dmfrancisco** [comment]
For context, here's a comparison with 1440x900 and 1920x1080 resolutions in Mac OS, the most common ones for our visitors.

![1](https://cloud.githubusercontent.com/assets/212106/16597666/0e17aedc-42f2-11e6-96cb-bc069cffbbab.png)
![2](https://cloud.githubusercontent.com/assets/212106/16597667/0e19430a-42f2-11e6-8ae5-54306713eca3.png)

![1](https://cloud.githubusercontent.com/assets/212106/16597721/498a7de6-42f2-11e6-820b-77cd4ca2cd76.png)
![2](https://cloud.githubusercontent.com/assets/212106/16597722/498e628a-42f2-11e6-8400-eac5d76fe227.png)
