### ISSUE TITLE
Make the "View on Github" link external

### ISSUE THREAD

**Issue by sushruth** [dmfrancisco/JS.coach#19]
I would like to be able to still be on the page while "View on GitHub" link opens in a new tab (irrespective of which tab steals focus).

(P.S. Please leave a comment if you think so too)

Thanks.

**Comment by dmfrancisco** [comment]
Hey @sushruth! This has been a recurring topic lately. There's an [open PR](https://github.com/dmfrancisco/JS.coach/pull/17) and a [closed issue](https://github.com/dmfrancisco/JS.coach/issues/18).

Personally I'm not a fan of `target="_blank"`, but I'm considering this and I'll get back to it soon.

The reason I dislike it is because I'm so used to `cmd+click` that I prefer to always have that control. When a link has `target="_blank"`, there isn't a way for the user to open the link in the same tab. Related to this, it seems to me that if we change the "View on GitHub" link we should also change the links inside the READMEs itself.

**Comment by sushruth** [comment]
Thank you. I use Windows which might have been the reason for my different view on this. Anyway, waiting to see if it gets through.

Cheers.
