### ISSUE TITLE
React-Help-Desk

### ISSUE THREAD

**Issue by unleashit** [dmfrancisco/JS.coach#403]
https://github.com/unleashit/React-Help-Desk

**Comment by dmfrancisco** [comment]
Sorry for taking so long to reply. I can't seem to find the package on the NPM registry. Is it published with a different name? I'll close this issue for now. Thanks for your contribution 👍

**Comment by unleashit** [comment]
React Help Desk isn't an NPM component. It has both client and server parts. I didn't see anywhere where you required this (your submission page has no instructions other than to post an issue). I thought this would be useful to the community being that I search high and low for a help desk style chat for React before I made this.

**Comment by dmfrancisco** [comment]
Okay, makes sense 👍  Unfortunately right now for the system to work, it has to be associated to a package published in the NPM registry. That's what I mean in the subsmission page with "please open an issue [here](#) and simply mention the NPM package name". Sorry for the confusion!

**Comment by unleashit** [comment]
Just some feedback, it would be helpful if you gave explicit instructions about the requirements like: "Requirements for submissions: 1) Must be an NPM package, 2) ... 3) ... ".

I remember reading the existing statement and getting the feeling since the directory seemed pretty comprehensive  like it probably wasn't an absolute requirement. 

You might change the language because it actually comes across a little presumptive like anything valuable having to do with React is or should be an installable NPM component. Honestly it doesn't bother me, but it might be nice to allow full client/server repos. I'm sure there are a lot of other projects besides mine that would be nice to useful in your directory, which is otherwise awesome!

**Comment by dmfrancisco** [comment]
@unleashit Completely agree 👍 There are several things that could be improved here, and the submission page is definitely one of them.

The automatic package discovery and some features like the versions and installs/mo currently depend on the package being published in the npmjs.com registry. But this means that projects that are a package but are not published there, or projects that simply can't be structured that way, can't be added right now. Which is a shame because there are some great projects like that.

It would be nice to improve JS.coach in order to support those projects, but right now it seems unlikely. Thank you for your feedback 👍
