### ISSUE TITLE
Misleading name for react native library itself

### ISSUE THREAD

**Issue by ahmed1490** [dmfrancisco/JS.coach#9]
https://js.coach/react-native/babel-preset-react-native

**Comment by dmfrancisco** [comment]
Ah, the package's [repository property](http://npm.im/package/babel-preset-react-native) is wrong. I remember fixing it manually but a bug in the scripts was resetting the custom repository I had specified manually. I wonder how many manual fixes got to lost because of this :sweat: Should be fixed now, thanks :+1:

**Comment by ahmed1490** [comment]
yeah i saw few more like that. One more was react-native-maps. 
Appreciate your work :)

**Comment by dmfrancisco** [comment]
Thanks! [`react-native-maps`](https://js.coach/react-native/react-native-maps) looks good now. I appreciate the help :smile:
